Try to get the automated release CI in shape

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,24 +1,13 @@
 on:
   release:
-    types: [ published ]
+    types: [published]
 
 name: Cargo Publish
 
 jobs:
-  publish:
-    if: false
-    name: Publish with ${{ matrix.os }}
-
-    strategy:
-      fail-fast: true
-      matrix:
-        include:
-          - os: ubuntu-latest
-            target: linux.x86_64
-          - os: macos-latest
-            target: macos
-
-    runs-on: ${{ matrix.os }}
+  publish_crate:
+    name: Cargo Publish
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v2
@@ -26,6 +15,26 @@ jobs:
         uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
+      - name: Publish crate
+        run: |
+          TAG_NAME=${{ github.event.release.tag_name }}
+          PREFIX=$(echo $TAG_NAME | cut -d'-' -f1)
+          case "$PREFIX" in
+            "sdf")
+              CRATE_NAME="sdf_glyph_renderer"
+              ;;
+            "tools")
+              CRATE_NAME="pbf_font_tools"
+              ;;
+            "cli")
+              CRATE_NAME="build_pbf_glyphs"
+              ;;
+            *)
+              echo "Invalid prefix in tag: $PREFIX"
+              exit 1
+          esac
+          cd $CRATE_NAME
+          cargo publish --all-features
       - name: Publish
         uses: actions-rs/cargo@v1
         env:
@@ -34,9 +43,18 @@ jobs:
           command: publish
           args: --all-features
 
-  build:
-    name: Build Binaries with ${{ matrix.os }}
-    if: false
+  publish_cli_binary:
+    name: Release build with ${{ matrix.os }}
+    if: startsWith(github.event.release.tag_name, 'cli-')
+    strategy:
+      fail-fast: true
+      # TODO: Not sure I agree with this setup of different runners; seems like we should use cross or something
+      matrix:
+        include:
+          - os: ubuntu-latest
+            target: x86_64-unknown-linux-gnu
+          - os: macos-latest
+            target: x86_64-apple-darwin
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout Repo
@@ -51,12 +69,6 @@ jobs:
           command: build
           args: --all-features --release
       - name: Push Artifacts
-        run: gh release upload $GITHUB_REF_NAME target/release/build_pbf_glyphs#build_pbf_glyphs.${{ matrix.target }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-#      - name: Publish on Release
-#        if: github.event.release.published == true
-#        env:
-#          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
-#        run: cargo publish -p pbf_font_tools --all-features
+        run: |
+          mv target/release/build_pbf_glyphs target/release/build_pbf_glyphs.${{ matrix.target }}
+          gh release upload ${{ github.event.release.tag_name }} target/release/build_pbf_glyphs.${{ matrix.target }}
